apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pjwa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-pjwa@sha256:b70db3913eb9e63096a8521d17626fa6159ef4b3c3b5c5f18a791f9507fd902b
        name: my-nodejs
        resources: {}
status: {}
